DROP DATABASE IF EXISTS subtweet;
CREATE DATABASE subtweet;

CREATE TABLE users {
    id INT PRIMARY KEY NOT NULL,
    screen_name VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL UNIQUE,
    profile_image VARCHAR(254) NOT NULL,
    created_at DEFAULT CURRENT_TIMESTAMP,
    updated_at DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
};

CREATE TABLE tweets {
    id INT PRIMARY KEY NOT NULL,
    user_id INT REFERENCES users(id) ON DELETE CASCADE
};