DROP DATABASE IF EXISTS subtweet;
CREATE DATABASE subtweet;

USE subtweet;

CREATE TABLE users (
    id INT PRIMARY KEY NOT NULL,
    screen_name VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(30) NOT NULL UNIQUE,
    profile_image VARCHAR(254) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tweets (
    id INT PRIMARY KEY NOT NULL,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    tweet VARCHAR(250) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);